export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const UPDATE_COMMON_FRIENDS = 'UPDATE_COMMON_FRIENDS';
export const UPDATE_COMMON_GROUPS = 'UPDATE_COMMON_GROUPS';
